import fs from "fs-extra"

export let emptyDir = (global.emptyDir = fs.emptyDir)
export let ensureFile = (global.ensureFile = fs.ensureFile)
export let ensureDir = (global.ensureDir = fs.ensureDir)
export let ensureLink = (global.ensureLink = fs.ensureLink)
export let ensureSymlink = (global.ensureSymlink = fs.ensureSymlink)
export let mkdirp = (global.mkdirp = fs.mkdirp)
export let mkdirs = (global.mkdirs = fs.mkdirs)
export let outputFile = (global.outputFile = fs.outputFile)
export let outputJson = (global.outputJson = fs.outputJson)
export let pathExists = (global.pathExists = fs.pathExists)
export let readJson = (global.readJson = fs.readJson)
export let remove = (global.remove = fs.remove)
export let writeJson = (global.writeJson = fs.writeJson)
