name: Publish globals

on:
  push:
    branches:
      - main
      - beta
      - alpha
    tags:
      - "*"

jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest]

    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Checkout globals
        uses: actions/checkout@master

      - name: npm i
        run: |
          npm i --legacy-peer-deps --no-audit

      - name: build
        run: |
          npm run build

      - name: Semantic Release
        run: |
          npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
